### ISSUE TITLE
Non-exploit usage inquiry

### ISSUE THREAD

**Issue by amiroux24** [checkraisefold/ROBLOXLink-Plugin#8]
Hello hope you're doing fine,

Me and my friends are trying some roblox roleplay however we are tired of writing on the roblox chat which is horrible and the voice chat feature just mutes you or warns you for no reason. 

So we wanted to try mumble however there was nothing except your work, so i've been wondering if there is any new update ? do we still have to exploit for it to work and if yes do we all have to exploit ? 

Thank you

**Comment by checkraisefold** [comment]
Unfortunately, the only method I've thought of to migrate this off of exploit-required usage (which is no longer viable with Hyperion) was parsing the Roblox log file, which is something Bloxstrap is doing for the optional per-game rich presence support. It would also require addition by the game owner.

The problem is I don't know how reasonably it can be done refresh-rate wise, along with the log file size getting massive (unless Roblox caps it). If I spend the time to investigate that, I will probably find that it's refresh rate limited, and it won't be very useful. As such, it's pretty much a shelved idea.
